import type { AppLocale } from "./locale";

/** نصوص الواجهة — عند اختيار EN يُستعمل الفرع الإنجليزي بالكامل حيث طُبّق. */
const AR = {
  landing: {
    nameAr: "عماراتي",
    tagline: "إدارة المباني الذكية",
    desc: "إدارة مبناك، انتخاب المشرفين، والتواصل مع مجتمعك.",
    login: "تسجيل الدخول",
    create: "إنشاء مبنى",
    langLabel: "English",
    logoAlt: "عماراتي",
  },
  login: {
    title: "تسجيل الدخول",
    subtitle: "أهلاً بك في عَمارتي. أدخل بريدك وكلمة مرورك للمتابعة.",
    emailVerified: "تم تأكيد بريدك. يمكنك الآن تسجيل الدخول.",
    email: "البريد",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    submit: "دخول",
    submitPending: "جاري تسجيل الدخول…",
    noAccount: "ليس لديك حساب؟",
    signUp: "أنشئ حساباً جديداً",
    noAccountFull: "لا يوجد حساب بهذا البريد. أنشئ حساباً جديداً.",
    verifyEmailFirst: "يرجى تأكيد البريد من الرابط المرسل قبل تسجيل الدخول.",
    invalidForm: "بيانات غير صالحة",
    invalidCredentials: "بريد أو كلمة مرور غير صحيحة",
    passwordMinForNew: "للحسابات الجديدة: كلمة المرور 6 أحرف على الأقل.",
    resendVerifyHint: "لم يصلك الرابط؟ أعد الإرسال من صفحة التحقق.",
    resendVerifyLink: "إعادة إرسال رابط التأكيد",
  },
  signup: {
    chooseTitle: "أنشئ حسابك",
    chooseSubtitle: "اختر طريقة البدء — يمكنك إنشاء مبنى جديد أو الانضمام إلى مبنى موجود.",
    choiceCreateTitle: "إنشاء مبنى جديد",
    choiceCreateDesc: "أنت منشئ المبنى وتريد تسجيل عمارتك بالعنوان الوطني وربط شقتك.",
    choiceJoinTitle: "الانضمام إلى مبنى",
    choiceJoinDesc: "لديك رمز مبنى من جار أو مالك — انضم لشقتك مباشرة.",
    haveAccount: "لديك حساب؟",
    backLogin: "تسجيل الدخول",
    yourInfoTitle: "بياناتك",
    buildingInfoTitle: "بيانات المبنى",
    joinInfoTitle: "بيانات الانضمام",
    submitCreate: "إنشاء الحساب وتسجيل المبنى",
    submitJoin: "إنشاء الحساب والانضمام",
    submitPending: "جاري المعالجة…",
    headerCreate: "إنشاء حساب — مبنى جديد",
    headerJoin: "إنشاء حساب — انضمام إلى مبنى",
    inviteCodeNotFound: "رمز المبنى غير صحيح أو غير موجود.",
    addressInvalid: "تحقق من العنوان الوطني والرمز البريدي (5 أرقام) وباقي الحقول",
    coordsInvalid: "إحداثيات الموقع غير صالحة",
    coordsBoth: "أدخل خط الطول والعرض معاً",
  },
  register: {
    title: "انضم إلى عَمارتي — حساب ساكن",
    name: "الاسم",
    email: "البريد",
    phone: "الجوال (اختياري)",
    password: "كلمة المرور",
    submit: "إنشاء الحساب",
    submitPending: "جاري إنشاء الحساب…",
    hasAccount: "لديك حساب؟",
    login: "دخول",
    invalidForm: "بيانات غير صالحة",
    emailTaken: "البريد مسجل مسبقاً",
    verifyAfterRegister:
      "بعد إنشاء الحساب نرسل رابط تحقق إلى بريدك. افتح الرابط ثم سجّل الدخول.",
    verifySendFailed:
      "تعذّر إرسال رسالة التحقق. راجع التفاصيل أدناه أو لوحة الخادم.",
    verifySendFailedNoUrl:
      "تعذّر بناء رابط التحقق. اضبط NEXT_PUBLIC_APP_URL في .env (مثل http://localhost:3000).",
    verifySendFailedNoSender:
      "وضع الإنتاج يتطلّب RESEND_API_KEY حقيقياً من resend.com/api-keys. أو استخدم npm run dev لطباعة الرابط في الطرفية.",
    verifySendFailedResend:
      "رفضت Resend الإرسال. راجع Logs في resend.com/emails؛ غالباً مفتاح منتهي أو بريد وهمي (مثل @example.com)، أو عنوان مرسل غير صالح.",
    verifySendFailedResendTestingRecipient:
      "وضع التجربة في Resend: مع onboarding@resend.dev يمكن الإرسال فقط إلى البريد نفسه المسجل في حسابك في Resend. سجّل في عَمارتي بنفس ذلك البريد، أو أكمل التحقق من نطاقك في Domains واستخدم from من نطاقك.",
    verifySendFailedResendFromDomain:
      "عنوان المرسل (RESEND_FROM_EMAIL) يجب أن يكون من نطاق مُفعَّل في Resend → Domains (SPF/DKIM). أو أعد التجربة بـ onboarding@resend.dev.",
    verifySendFailedResendInvalidKey:
      "رفض Resend المفتاح (منتهي، محذوف، أو غير صالح). أنشئ مفتاحاً جديداً Full access من resend.com/api-keys وحدّث RESEND_API_KEY ثم أعد تشغيل السيرفر.",
    verifySendFailedResendBlockedEmail:
      "لا يمكن الإرسال إلى نطاق بريد وهمي تجريبي (غالباً @example.com). استخدم بريداً حقيقياً أو عناوين Resend مثل delivered@resend.dev.",
  },
  registerCheckEmail: {
    title: "تحقق من بريدك",
    bodyBefore: "أرسلنا رابطاً لتأكيد البريد. افتح الرسالة واضغط الرابط ثم عد إلى",
    loginLink: "تسجيل الدخول",
    bodyAfter: ".",
    resendTitle: "إعادة إرسال الرابط",
    resendHint: "أدخل بريدك المسجّل لإرسال رابط تحقق جديد (صالح 24 ساعة).",
    resendEmailLabel: "البريد",
    resendSubmit: "إرسال الرابط",
    resentOk: "إن وُجد حساب غير مُفعّل لذلك البريد، أرسلنا رابطاً جديداً.",
    resendInvalidEmail: "أدخل بريداً صالحاً",
    resendAlreadyVerified: "هذا البريد مُفعّل مسبقاً. يمكنك تسجيل الدخول.",
    resendSendFailed:
      "تعذّر إرسال البريد. تحقق من الإعدادات أو راجع سجل الخادم (في التطوير يُطبع الرابط في الطرفية).",
  },
  verifyEmail: {
    invalidTitle: "رابط غير صالح",
    invalidBody: "لم نجد رمز التحقق. اطلب إعادة التسجيل أو راجع الرابط في البريد.",
    goLogin: "الذهاب لتسجيل الدخول",
    linkExpired: "انتهت صلاحية رابط التحقق أو غير صالح",
  },
  dashboard: {
    title: "ابدأ مع عَمارتي",
    subtitle: "أنشئ مبناك للمرة الأولى أو انضم برمز مبنى جاهز.",
    titleMy: "مبانيك",
    subtitleMy: "اختر المبنى لفتح لوحته (الصيانة، التصويت، الإعلانات، المدفوعات).",
    firstTimeHint:
      "هذه الخطوة تظهر لمرة واحدة فقط. بعد إنشاء أو الانضمام لأول مبنى ستفتح اللوحة مباشرة عند تسجيل الدخول.",
    createBuilding: "إنشاء مبنى جديد",
    splHintBefore: "أدخل بيانات العنوان الوطني وفق معايير البريد السعودي (",
    splLink: "العنوان الوطني",
    splHintAfter:
      "). الرمز البريدي خمسة أرقام؛ الرقم المختصر 8 خانات عند توفره.",
    name: "اسم العمارة",
    namePh: "مثال: عمارة النور",
    region: "المنطقة",
    regionPh: "مثال: منطقة الرياض",
    city: "المدينة",
    cityPh: "مثال: الرياض",
    district: "الحي",
    streetName: "اسم الشارع",
    buildingNumber: "رقم المبنى",
    additionalNumber: "الرقم الإضافي (اختياري)",
    postalCode: "الرمز البريدي (5 أرقام)",
    shortAddressCode: "الرمز المختصر (8 خانات، اختياري)",
    geoHint:
      "تحديد الموقع (اختياري): الصق خط العرض وخط الطول من خرائط Google أو أي تطبيق خرائط.",
    latitude: "خط العرض",
    longitude: "خط الطول",
    unitLabel: "رقم شقتك",
    unitPh: "مثال: 303",
    createSubmit: "إنشاء المبنى وربط شقتك",
    joinCard: "الانضمام برمز المبنى",
    joinHint:
      "أي ساكن يشارك رمز المبنى العام معك — أدخل رقم شقتك أو أنشئ وحدة جديدة.",
    inviteCode: "رمز المبنى",
    unitNumber: "رقم الشقة",
    joinSubmit: "انضمام",
    buildingsCard: "مبانيك",
    noBuildings: "لا توجد مبانٍ بعد. أنشئ مبنى أو انضم برمز.",
    unit: "شقة",
    owner: "مالك",
    tenant: "مستأجر",
    supervisor: "مشرف",
    open: "فتح",
    openBuilding: "فتح لوحة المبنى",
    openBuildingAria: "فتح لوحة المبنى",
  },
  buildingLayout: {
    building: "المبنى",
    postal: "الرمز البريدي",
    inviteCode: "رمز الدعوة",
    mapLink: "فتح الموقع على الخريطة",
    allBuildings: "كل المبانى",
  },
  buildingNav: {
    overview: "نظرة عامة",
    maintenance: "صيانة",
    votes: "تصويت",
    payments: "مدفوعات",
    announcements: "إعلانات",
    chat: "محادثة",
    passport: "جواز الشقة",
    invite: "دعوات",
    supervisor: "لوحة المشرف",
  },
  buildingHome: {
    yourStatus: "حالتك في هذا المبنى",
    youSupervisor: "أنت المشرف",
    currentSupervisor: "المشرف الحالي",
    noSupervisor:
      "لا يوجد مشرف محدد. يمكن لمنشئ المبنى التعيين أو فتح تصويت من قسم التصويت.",
    unitPrefix: "شقة",
    assignHint: "تعيين مشرف (صلاحية منشئ المبنى)",
    chooseMember: "اختر عضواً",
    assignSubmit: "تعيين كن مشرف",
    startVote: "بدء تصويت لاختيار مشرف",
    ownersRequired: "يتطلب مالكين فأكثر",
    shortcuts: "اختصارات سريعة",
    linkMaintenance: "تقديم طلب صيانة",
    linkVotes: "التصويتات",
    linkInvite: "رمز المبنى",
    linkPublicCode: "مشاركة رمز المبنى",
    overviewSection: "نظرة عامة",
    aiAssistantSection: "المساعد الذكي",
    socialSection: "المحادثات والإعلانات",
    chatTitle: "محادثة السكان",
    announcementsTitle: "آخر الإعلانات",
    openChat: "فتح المحادثة",
    openAnnouncements: "فتح الإعلانات",
    openInvite: "مشاركة رمز المبنى",
    noChatYet: "لا رسائل بعد — ابدأ المحادثة من قسم المحادثة.",
    noAnnouncementsYet: "لا إعلانات بعد.",
    moreCount: "المزيد",
    supervisorOverviewTitle: "صحة المبنى — لوحة المشرف",
    supervisorOverviewHint:
      "ملخّص سريع للمشرف: السكور الشهري لصحة المبنى وتنبيهات الصيانة التنبؤية.",
  },
  maintenance: {
    newRequest: "طلب صيانة جديد",
    aiHint:
      "يحلّل النموذج التنبؤي (Amarati AI / RandomForest) وصف المشكلة ويقترح أفضل شركات الصيانة المرشّحة في مكة بناءً على نوع العطل.",
    type: "النوع",
    scopePersonal: "صيانة شخصية (شقتك)",
    scopeCommunity: "صيانة مجتمعية (مشتركة)",
    title: "عنوان مختصر",
    problem: "وصف المشكلة",
    submitAi: "إرسال مع تحليل وتوصيات الذكاء الاصطناعي",
    requests: "الطلبات",
    noneRequests: "لا طلبات صيانة بعد.",
    personalUnit: "شخصي — شقة",
    community: "مجتمعي",
    status: "الحالة",
    analysis: "تحليل",
    suggestions: "توصيات",
    aiTag: "تحليل ذكاء اصطناعي",
    aiCompanies: "شركات صيانة موصى بها (نموذج Amarati AI):",
    startCompanyVote: "بدء تصويت لاختيار شركة صيانة",
    companyVoteOpen: "يوجد تصويت مفتوح لشركة الصيانة — تابع من قسم «تصويت».",
    scopeLabelPersonal: "شخصي",
    scopeLabelCommunity: "مجتمعي",
  },
  chat: {
    title: "محادثة السكان (اختيارية)",
    back: "العودة للمبنى",
    hint: "دردشة بسيطة داخل المبنى — يمكن تعطيلها لاحقاً أو استبدالها بخدمة متخصصة.",
    placeholder: "رسالة...",
    send: "إرسال",
  },
  votes: {
    title: "التصويتات",
    titleSupervisor: "تصويت اختيار المشرف",
    titleCompany: "تصويت شركات الصيانة (الأعطال المجتمعية)",
    titleOther: "تصويتات أخرى",
    kindsTitle: "خيارات التصويت",
    kindsHint: "في عَمارتي يوجد نوعان من التصويت: اختيار مشرف المبنى، واختيار شركة صيانة لطلبات الصيانة المجتمعية.",
    kindSupervisorTitle: "تصويت لاختيار مشرف",
    kindSupervisorDesc: "يصوّت الملاك على من يدير المبنى. يفتحه منشئ المبنى.",
    kindCompanyTitle: "تصويت شركة صيانة (مجتمعي)",
    kindCompanyDesc: "افتح طلب صيانة مجتمعي ثم ابدأ تصويتاً على الشركات التي رشّحها نموذج الذكاء الاصطناعي.",
    creatorOnlyHint: "يحق لمنشئ المبنى فقط بدء تصويت المشرف.",
    openMaintenance: "فتح قسم الصيانة لاختيار طلب",
    typeSupervisor: "مشرف",
    typeCompany: "شركة صيانة",
    typeLegacyPoll: "تصويت (أرشيف)",
    open: "مفتوح",
    closed: "مغلق",
    ends: "ينتهي",
    votes: "صوت",
    vote: "صوّت",
    yourVote: "صوتك هنا",
    startSupervisor: "بدء تصويت المشرف",
    closeSupervisor: "إغلاق وتعيين المشرف الفائز",
    closeCompany: "إغلاق التصويت وتسجيل الشركة الفائزة",
    none: "لا تصويتات بعد.",
  },
  supervisor: {
    only: "هذه الصفحة للمشرف فقط.",
    panelTitle: "لوحة المشرف",
    refreshTitle: "تحديث السكور والتنبؤات",
    refreshP1:
      "زر «تحديث الآن» يُحدّث سكور الصحة الشهري من سجل طلبات الصيانة، ويُضيف تنبيهات استباقية تجريبية. التقرير نفسه يظهر في البطاقات أدناه (الشهر/التنبيهات/جدول الطلبات) — لا حاجة لرفع ملف منفصل.",
    refreshP2:
      "لربط نموذج من Colab أو أي خدمة: انشر API يرجع JSON واضبط MAINTENANCE_ML_API_URL في البيئة (العقد موثّق في ml-inference.ts).",
    refreshP3:
      "يمكن ربط نموذج تنبؤ خارجي عبر المتغير MAINTENANCE_ML_API_URL (راجع ml-inference.ts).",
    refreshBtn: "تحديث الآن",
    scoreTitle: "سجل السكور الشهري",
    scoreEmpty: "اضغط تحديث لإنشاء أول سجل.",
    alertsTitle: "تنبيهات صيانة تنبؤية",
    reportTitle: "تقرير سريع (تصدير يدوي)",
    reportHint:
      "هذا الجدول يُبنى تلقائياً من آخر طلبات الصيانة في المبنى (حد أقصى 15 صفاً). للتحديث بعد طلبات جديدة يكفي إعادة فتح الصفحة أو الضغط على «تحديث الآن» أعلاه إن أردت تحديث السكور والتنبيهات أيضاً.",
    thTitle: "العنوان",
    thScope: "النطاق",
    thStatus: "الحالة",
  },
  announcements: {
    new: "إعلان جديد",
    titlePh: "عنوان الإعلان",
    bodyPh: "تفاصيل...",
    publish: "نشر",
    recent: "آخر الإعلانات",
  },
  payments: {
    log: "سجل المدفوعات",
    none: "لا مدفوعات مسجلة بعد.",
    mockTitle: "دفع تجريبي عبر التطبيق",
    mockHint: "للتوضيح فقط — اربط لاحقاً بوابة دفع محلية (مدى، STC Pay، إلخ).",
    amount: "المبلغ (ريال)",
    desc: "البيان",
    descPh: "اشتراك صيانة / سداد...",
    linkMaint: "ربط بطلب صيانة (اختياري)",
    noneOpt: "—",
    mockSubmit: "تسجيل دفع ناجح (تجريبي)",
  },
  passport: {
    title: "جواز رقمي — شقة",
    subtitle: "سجل الإصلاحات والطلبات المرتبطة بهذه الوحدة.",
    none: "لا أحداث بعد.",
  },
  invitePage: {
    publicCode: "رمز المبنى العام",
    shareHintBefore: "شارك الرمز مع الجيران لينضموا برقم شقتهم:",
    publicOnlyHint:
      "تمت إزالة الدعوة عبر الروابط — اعتمد على رمز المبنى أعلاه فقط. أي ساكن يدخله من شاشة الانضمام مع رقم شقته.",
    tenantCard: "دعوات المستأجرين",
    tenantOnly:
      "حسابك مستأجر — يمكنك مشاركة رمز المبنى العام مع باقي السكان.",
  },
  join: {
    invalidTitle: "رابط غير صالح",
    expired: "قد يكون منتهي الصلاحية.",
    backDashboard: "العودة للوحة التحكم",
    inviteTitle: "دعوة للانضمام",
    building: "المبنى",
    unit: "الشقة",
    kind: "النوع",
    accept: "قبول والانضمام",
  },
  profile: {
    title: "الملف الشخصي",
    subtitle: "معلومات حسابك وإعداداتك.",
    accountTitle: "بيانات الحساب",
    name: "الاسم",
    email: "البريد",
    phone: "الجوال (اختياري)",
    save: "حفظ التغييرات",
    saving: "جاري الحفظ…",
    saved: "تم حفظ بياناتك.",
    invalidForm: "بيانات غير صالحة. يجب أن يكون الاسم حرفين فأكثر.",
    emailVerifiedYes: "بريدك مؤكَّد.",
    emailVerifiedNo: "البريد غير مؤكَّد بعد.",
    resendVerification: "إعادة إرسال رابط التأكيد",
    settingsTitle: "الإعدادات",
    settingsHint:
      "اختر المظهر واللغة وتفضيلات الإشعارات. تُحفظ على هذا الجهاز.",
    themeLabel: "المظهر",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeSystem: "النظام",
    languageLabel: "اللغة",
    notificationsLabel: "إشعارات المتصفح",
    notificationsOn: "مفعّلة",
    notificationsOff: "متوقفة",
    notificationsHint:
      "نطلب إذن المتصفح عند التفعيل. يمكنك إيقافها في أي وقت.",
    sessionTitle: "الجلسة",
    sessionHint: "تسجيل الخروج من هذا الجهاز.",
    logout: "تسجيل الخروج",
    memberSince: "عضو منذ",
    passportTitle: "جواز الشقة",
    passportHint: "سجل الإصلاحات والطلبات لكل وحدة لديك.",
    passportNoUnits: "لم تنضم إلى أي مبنى بعد.",
    passportNoEvents: "لا أحداث مسجَّلة لهذه الوحدة بعد.",
    passportOpen: "فتح جواز الوحدة",
    notificationsCardTitle: "الإعدادات",
  },
} as const;

type Messages = typeof AR;

const EN = {
  landing: {
    nameAr: "عماراتي",
    tagline: "Smart building management",
    desc: "Manage your building, elect supervisors, and connect with your community.",
    login: "Log in",
    create: "Create building",
    langLabel: "عربي",
    logoAlt: "Amarati",
  },
  login: {
    title: "Log in",
    subtitle: "Welcome back to Amarati. Enter your email and password to continue.",
    emailVerified: "Your email is verified. You can sign in now.",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    submit: "Sign in",
    submitPending: "Signing in…",
    noAccount: "Don’t have an account?",
    signUp: "Create a new account",
    noAccountFull: "No account with this email. Create a new account.",
    verifyEmailFirst: "Please confirm your email using the link we sent before signing in.",
    invalidForm: "Invalid data",
    invalidCredentials: "Incorrect email or password",
    passwordMinForNew: "New accounts need a password of at least 6 characters.",
    resendVerifyHint: "Didn’t get the email? Resend the link from the verification page.",
    resendVerifyLink: "Resend confirmation link",
  },
  signup: {
    chooseTitle: "Create your account",
    chooseSubtitle:
      "Pick how you want to start — register a new building or join one with a code.",
    choiceCreateTitle: "Register a new building",
    choiceCreateDesc:
      "You’re the building creator and want to register the address and link your unit.",
    choiceJoinTitle: "Join a building",
    choiceJoinDesc: "You have a code from a neighbour — join your unit directly.",
    haveAccount: "Already have an account?",
    backLogin: "Log in",
    yourInfoTitle: "Your details",
    buildingInfoTitle: "Building details",
    joinInfoTitle: "Join details",
    submitCreate: "Create account & register building",
    submitJoin: "Create account & join",
    submitPending: "Working…",
    headerCreate: "Create account — new building",
    headerJoin: "Create account — join building",
    inviteCodeNotFound: "Building code is invalid or not found.",
    addressInvalid: "Check the national address, postal code (5 digits) and other fields.",
    coordsInvalid: "Invalid coordinates.",
    coordsBoth: "Enter both latitude and longitude.",
  },
  register: {
    title: "Join Amarati — resident account",
    name: "Name",
    email: "Email",
    phone: "Phone (optional)",
    password: "Password",
    submit: "Create account",
    submitPending: "Creating account…",
    hasAccount: "Already have an account?",
    login: "Log in",
    invalidForm: "Invalid data",
    emailTaken: "This email is already registered",
    verifyAfterRegister:
      "After you sign up we send a confirmation link to your email. Open it, then sign in.",
    verifySendFailed:
      "Could not send the verification email. See the message below or the server log.",
    verifySendFailedNoUrl:
      "Could not build the verification link. Set NEXT_PUBLIC_APP_URL in .env (e.g. http://localhost:3000).",
    verifySendFailedNoSender:
      "Production requires a real RESEND_API_KEY from resend.com/api-keys. Or use npm run dev to print the link in the terminal.",
    verifySendFailedResend:
      "Resend rejected the send. Check Logs at resend.com/emails — often an invalid key, a disposable test address (e.g. @example.com), or an invalid from address.",
    verifySendFailedResendTestingRecipient:
      "Resend test mode: with onboarding@resend.dev you may only send to the same email as your Resend account. Register using that address, or verify a domain in Resend → Domains and set RESEND_FROM_EMAIL on that domain.",
    verifySendFailedResendFromDomain:
      "RESEND_FROM_EMAIL must use a domain you verified in Resend → Domains (SPF/DKIM). Or use onboarding@resend.dev for initial testing.",
    verifySendFailedResendInvalidKey:
      "Resend rejected the API key (revoked, wrong, or missing). Create a new key with Full access at resend.com/api-keys, update RESEND_API_KEY, and restart the server.",
    verifySendFailedResendBlockedEmail:
      "That recipient domain is blocked for testing (e.g. @example.com). Use a real inbox or a Resend test address like delivered@resend.dev.",
  },
  registerCheckEmail: {
    title: "Check your email",
    bodyBefore: "We sent a confirmation link. Open it, then return to",
    loginLink: "log in",
    bodyAfter: ".",
    resendTitle: "Resend link",
    resendHint: "Enter the email you registered with to receive a new link (valid 24 hours).",
    resendEmailLabel: "Email",
    resendSubmit: "Send link",
    resentOk: "If there is an unverified account for that address, we sent a new link.",
    resendInvalidEmail: "Enter a valid email address",
    resendAlreadyVerified: "This email is already verified. You can sign in.",
    resendSendFailed:
      "Could not send the email. Check your settings or the server log (in development the link is printed in the terminal).",
  },
  verifyEmail: {
    invalidTitle: "Invalid link",
    invalidBody: "No verification token found. Register again or use the link from your email.",
    goLogin: "Go to log in",
    linkExpired: "This verification link has expired or is invalid.",
  },
  dashboard: {
    title: "Get started with Amarati",
    subtitle: "Register your first building or join one with a code.",
    titleMy: "Your buildings",
    subtitleMy: "Pick a building to open its dashboard (maintenance, voting, announcements, payments).",
    firstTimeHint:
      "This step appears only the first time. Once you create or join a building, the dashboard opens directly when you sign in.",
    createBuilding: "Create a new building",
    splHintBefore: "Enter national address details per Saudi Post (",
    splLink: "National Address",
    splHintAfter:
      "). Postal code is 5 digits; short code 8 characters when available.",
    name: "Building name",
    namePh: "e.g. Al-Noor Tower",
    region: "Region",
    regionPh: "e.g. Riyadh Region",
    city: "City",
    cityPh: "e.g. Riyadh",
    district: "District",
    streetName: "Street name",
    buildingNumber: "Building number",
    additionalNumber: "Additional number (optional)",
    postalCode: "Postal code (5 digits)",
    shortAddressCode: "Short address code (8 chars, optional)",
    geoHint: "Optional: paste latitude and longitude from Google Maps or any maps app.",
    latitude: "Latitude",
    longitude: "Longitude",
    unitLabel: "Your unit number",
    unitPh: "e.g. 303",
    createSubmit: "Create building and link my unit",
    joinCard: "Join with building code",
    joinHint:
      "If a resident shared the public building code — enter your unit number or create a new unit.",
    inviteCode: "Building code",
    unitNumber: "Unit number",
    joinSubmit: "Join",
    buildingsCard: "Your buildings",
    noBuildings: "No buildings yet. Create one or join with a code.",
    unit: "Unit",
    owner: "Owner",
    tenant: "Tenant",
    supervisor: "Supervisor",
    open: "Open",
    openBuilding: "Open building dashboard",
    openBuildingAria: "Open building dashboard",
  },
  buildingLayout: {
    building: "Building",
    postal: "Postal code",
    inviteCode: "Invite code",
    mapLink: "Open on map",
    allBuildings: "All buildings",
  },
  buildingNav: {
    overview: "Overview",
    maintenance: "Maintenance",
    votes: "Votes",
    payments: "Payments",
    announcements: "Announcements",
    chat: "Chat",
    passport: "Unit passport",
    invite: "Invites",
    supervisor: "Supervisor",
  },
  buildingHome: {
    yourStatus: "Your status in this building",
    youSupervisor: "You are the supervisor",
    currentSupervisor: "Current supervisor",
    noSupervisor:
      "No supervisor assigned yet. The building creator can assign one or open a vote under Votes.",
    unitPrefix: "Unit",
    assignHint: "Assign supervisor (building creator only)",
    chooseMember: "Choose a member",
    assignSubmit: "Set as supervisor",
    startVote: "Start vote to elect supervisor",
    ownersRequired: "Requires two or more owners",
    shortcuts: "Quick shortcuts",
    linkMaintenance: "Submit maintenance request",
    linkVotes: "Votes",
    linkInvite: "Building code",
    linkPublicCode: "Share building code",
    overviewSection: "Overview",
    aiAssistantSection: "AI Assistant",
    socialSection: "Chat & announcements",
    chatTitle: "Resident chat",
    announcementsTitle: "Latest announcements",
    openChat: "Open chat",
    openAnnouncements: "Open announcements",
    openInvite: "Share building code",
    noChatYet: "No messages yet — open the chat to start a conversation.",
    noAnnouncementsYet: "No announcements yet.",
    moreCount: "more",
    supervisorOverviewTitle: "Building health — supervisor panel",
    supervisorOverviewHint:
      "Quick supervisor summary: monthly health score and predictive maintenance alerts.",
  },
  maintenance: {
    newRequest: "New maintenance request",
    aiHint:
      "The Amarati AI predictive model (RandomForest) analyses your description and recommends the best matching maintenance companies in Makkah.",
    type: "Type",
    scopePersonal: "Personal (your unit)",
    scopeCommunity: "Community (shared)",
    title: "Short title",
    problem: "Problem description",
    submitAi: "Submit with AI analysis & recommendations",
    requests: "Requests",
    noneRequests: "No maintenance requests yet.",
    personalUnit: "Personal — unit",
    community: "Community",
    status: "Status",
    analysis: "Analysis",
    suggestions: "Suggestions",
    aiTag: "AI analysis",
    aiCompanies: "Recommended maintenance companies (Amarati AI):",
    startCompanyVote: "Start vote to pick a maintenance company",
    companyVoteOpen: "A maintenance company vote is open — open the Voting tab.",
    scopeLabelPersonal: "Personal",
    scopeLabelCommunity: "Community",
  },
  chat: {
    title: "Resident chat (optional)",
    back: "Back to building",
    hint: "Simple in-building chat — can be replaced with a dedicated service later.",
    placeholder: "Message…",
    send: "Send",
  },
  votes: {
    title: "Votes",
    titleSupervisor: "Supervisor election votes",
    titleCompany: "Maintenance-company votes (community issues)",
    titleOther: "Other votes",
    kindsTitle: "Vote types",
    kindsHint: "Amarati supports two vote types: pick a building supervisor, and pick a maintenance company for a community-scoped maintenance request.",
    kindSupervisorTitle: "Supervisor election",
    kindSupervisorDesc: "Owners vote on who runs the building. Started by the building creator.",
    kindCompanyTitle: "Maintenance-company vote (community)",
    kindCompanyDesc: "Open a community maintenance request, then start a vote on the AI-recommended companies.",
    creatorOnlyHint: "Only the building creator can start a supervisor vote.",
    openMaintenance: "Open maintenance to pick a request",
    typeSupervisor: "Supervisor",
    typeCompany: "Maintenance company",
    typeLegacyPoll: "Poll (archive)",
    open: "Open",
    closed: "Closed",
    ends: "Ends",
    votes: "votes",
    vote: "Vote",
    yourVote: "Your vote",
    startSupervisor: "Start supervisor vote",
    closeSupervisor: "Close and assign winning supervisor",
    closeCompany: "Close vote and record the winning company",
    none: "No votes yet.",
  },
  supervisor: {
    only: "Supervisors only.",
    panelTitle: "Supervisor panel",
    refreshTitle: "Refresh score & predictions",
    refreshP1:
      "“Update now” refreshes the monthly health score from maintenance history and adds sample predictive alerts. The report appears below — no separate file upload.",
    refreshP2:
      "To use a Colab or other ML model: deploy a JSON API and set MAINTENANCE_ML_API_URL (see ml-inference.ts for the request/response contract).",
    refreshP3:
      "You can plug in an external prediction API via MAINTENANCE_ML_API_URL (see ml-inference.ts).",
    refreshBtn: "Update now",
    scoreTitle: "Monthly score history",
    scoreEmpty: "Click update to create the first record.",
    alertsTitle: "Predictive maintenance alerts",
    reportTitle: "Quick report (manual export)",
    reportHint:
      "This table is built from the latest maintenance requests (max 15 rows). Refresh the page after new requests, or click “Update now” above to refresh scores and alerts.",
    thTitle: "Title",
    thScope: "Scope",
    thStatus: "Status",
  },
  announcements: {
    new: "New announcement",
    titlePh: "Title",
    bodyPh: "Details…",
    publish: "Publish",
    recent: "Recent announcements",
  },
  payments: {
    log: "Payment history",
    none: "No payments yet.",
    mockTitle: "Mock in-app payment",
    mockHint: "For demo only — connect a real gateway later (Mada, STC Pay, etc.).",
    amount: "Amount (SAR)",
    desc: "Description",
    descPh: "Maintenance fee / payment…",
    linkMaint: "Link to maintenance request (optional)",
    noneOpt: "—",
    mockSubmit: "Record successful payment (demo)",
  },
  passport: {
    title: "Digital passport — unit",
    subtitle: "Repairs and requests linked to this unit.",
    none: "No events yet.",
  },
  invitePage: {
    publicCode: "Public building code",
    shareHintBefore: "Share this code so neighbours can join with their unit number:",
    publicOnlyHint:
      "Tenant invite-by-link has been removed — share the building code above. Residents enter it from the Join screen with their unit number.",
    tenantCard: "Tenant invites",
    tenantOnly:
      "You are a tenant — you can share the public building code with other residents.",
  },
  join: {
    invalidTitle: "Invalid link",
    expired: "It may have expired.",
    backDashboard: "Back to dashboard",
    inviteTitle: "Invitation to join",
    building: "Building",
    unit: "Unit",
    kind: "Role",
    accept: "Accept and join",
  },
  profile: {
    title: "Profile",
    subtitle: "Your account info and settings.",
    accountTitle: "Account details",
    name: "Name",
    email: "Email",
    phone: "Phone (optional)",
    save: "Save changes",
    saving: "Saving…",
    saved: "Your profile has been updated.",
    invalidForm: "Invalid data. Name must be at least 2 characters.",
    emailVerifiedYes: "Email verified.",
    emailVerifiedNo: "Email not verified yet.",
    resendVerification: "Resend confirmation link",
    settingsTitle: "Settings",
    settingsHint:
      "Pick a theme, language, and notification preferences. Saved on this device.",
    themeLabel: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    languageLabel: "Language",
    notificationsLabel: "Browser notifications",
    notificationsOn: "On",
    notificationsOff: "Off",
    notificationsHint:
      "We ask the browser for permission when you enable. You can turn off any time.",
    sessionTitle: "Session",
    sessionHint: "Sign out from this device.",
    logout: "Log out",
    memberSince: "Member since",
    passportTitle: "Unit passport",
    passportHint: "Repair and request history for every unit you belong to.",
    passportNoUnits: "You have not joined any building yet.",
    passportNoEvents: "No events recorded for this unit yet.",
    passportOpen: "Open unit passport",
    notificationsCardTitle: "Settings",
  },
} as unknown as Messages;

export function ui(locale: AppLocale): Messages {
  return locale === "en" ? EN : AR;
}

export function pickDateLocale(locale: AppLocale): string {
  return locale === "en" ? "en-US" : "ar-SA";
}
