import type { AppLocale } from "./locale";

/** نصوص الواجهة — عند اختيار EN يُستعمل الفرع الإنجليزي بالكامل حيث طُبّق. */
const AR = {
  landing: {
    nameAr: "عماراتي",
    tagline: "إدارة المباني الذكية",
    desc: "إدارة المباني الذكية",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    create: "إنشاء مبنى",
    langLabel: "English",
    logoAlt: "عماراتي",
  },
  login: {
    title: "تسجيل الدخول",
    subtitle: "",
    emailVerified: "تم تأكيد بريدك. يمكنك الآن تسجيل الدخول.",
    identifier: "الجوال أو البريد",
    email: "البريد",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    submit: "دخول",
    submitPending: "جاري تسجيل الدخول…",
    noAccount: "ليس لديك حساب؟",
    signUp: "أنشئ حساباً جديداً",
    noAccountFull: "لا يوجد حساب بهذا الجوال أو البريد.",
    verifyEmailFirst:
      "يرجى تأكيد البريد من الرابط المرسل، أو تأكيد الجوال برمز OTP من صفحة «تحقق من الجوال»، قبل تسجيل الدخول.",
    invalidForm: "بيانات غير صالحة",
    invalidCredentials: "رقم الجوال أو البريد أو كلمة المرور غير صحيحة",
    passwordMinForNew: "للحسابات الجديدة: كلمة المرور 6 أحرف على الأقل.",
    resendVerifyHint: "لم يصلك الرابط؟ أعد الإرسال من صفحة التحقق.",
    resendVerifyLink: "إعادة إرسال رابط التأكيد",
  },
  signup: {
    chooseTitle: "أنشئ حسابك",
    chooseSubtitle: "انضم إلى عمارتك برمز المبنى ورقم شقتك.",
    choiceCreateTitle: "إنشاء مبنى جديد",
    choiceCreateDesc: "تسجيل عمارة جديدة ومشاركة رمز الدعوة مع السكان.",
    choiceJoinTitle: "الانضمام إلى مبنى",
    choiceJoinDesc: "انضم إلى عمارتك برمز المبنى ورقم شقتك.",
    haveAccount: "لديك حساب؟",
    backLogin: "تسجيل الدخول",
    yourInfoTitle: "بياناتك",
    buildingInfoTitle: "بيانات المبنى",
    joinInfoTitle: "بيانات الانضمام",
    submitCreate: "إنشاء الحساب وتسجيل المبنى",
    submitJoin: "إنشاء الحساب والانضمام",
    submitPending: "جاري المعالجة…",
    headerCreate: "إنشاء حساب — مبنى جديد",
    headerJoin: "إنشاء حساب — انضمام إلى مبنى",
    inviteCodeNotFound: "رمز المبنى غير صحيح أو غير موجود.",
    addressInvalid:
      "تحقق من اسم العمارة ورقم الشقة وحقول العنوان الوطني (المنطقة، المدينة، الحي، الشارع، رقم المبنى، الرمز البريدي).",
  },
  register: {
    title: "انضم إلى عَمارتي — حساب ساكن",
    name: "الاسم",
    email: "البريد (اختياري)",
    phone: "الجوال (إلزامي)",
    password: "كلمة المرور",
    submit: "إنشاء الحساب",
    submitPending: "جاري إنشاء الحساب…",
    hasAccount: "لديك حساب؟",
    login: "دخول",
    invalidForm: "بيانات غير صالحة",
    emailTaken: "البريد مسجل مسبقاً",
    phoneTaken: "رقم الجوال مسجل مسبقاً",
    verifyAfterRegister:
      "بعد إنشاء الحساب نرسل رابط تحقق إلى بريدك. افتح الرابط ثم سجّل الدخول.",
    verifySendFailed:
      "تعذّر إرسال رسالة التحقق. راجع التفاصيل أدناه أو لوحة الخادم.",
    verifySendFailedNoUrl:
      "تعذّر بناء رابط التحقق. اضبط NEXT_PUBLIC_APP_URL في .env (مثل http://localhost:3000).",
    verifySendFailedNoSender:
      "وضع الإنتاج يتطلّب RESEND_API_KEY حقيقياً من resend.com/api-keys. أو استخدم npm run dev لطباعة الرابط في الطرفية.",
    verifySendFailedResend:
      "رفضت Resend الإرسال. راجع Logs في resend.com/emails؛ غالباً مفتاح منتهي أو بريد وهمي (مثل @example.com)، أو عنوان مرسل غير صالح.",
    verifySendFailedResendTestingRecipient:
      "وضع التجربة في Resend: مع onboarding@resend.dev يمكن الإرسال فقط إلى البريد نفسه المسجل في حسابك في Resend. سجّل في عَمارتي بنفس ذلك البريد، أو أكمل التحقق من نطاقك في Domains واستخدم from من نطاقك.",
    verifySendFailedResendFromDomain:
      "عنوان المرسل (RESEND_FROM_EMAIL) يجب أن يكون من نطاق مُفعَّل في Resend → Domains (SPF/DKIM). أو أعد التجربة بـ onboarding@resend.dev.",
    verifySendFailedResendInvalidKey:
      "رفض Resend المفتاح (منتهي، محذوف، أو غير صالح). أنشئ مفتاحاً جديداً Full access من resend.com/api-keys وحدّث RESEND_API_KEY ثم أعد تشغيل السيرفر.",
    verifySendFailedResendBlockedEmail:
      "لا يمكن الإرسال إلى نطاق بريد وهمي تجريبي (غالباً @example.com). استخدم بريداً حقيقياً أو عناوين Resend مثل delivered@resend.dev.",
  },
  registerCheckEmail: {
    title: "تحقق من بريدك",
    bodyBefore: "أرسلنا رابطاً لتأكيد البريد. افتح الرسالة واضغط الرابط ثم عد إلى",
    loginLink: "تسجيل الدخول",
    bodyAfter: ".",
    resendTitle: "إعادة إرسال الرابط",
    resendHint: "أدخل بريدك المسجّل لإرسال رابط تحقق جديد (صالح 24 ساعة).",
    resendEmailLabel: "البريد",
    resendSubmit: "إرسال الرابط",
    resentOk: "إن وُجد حساب غير مُفعّل لذلك البريد، أرسلنا رابطاً جديداً.",
    resendInvalidEmail: "أدخل بريداً صالحاً",
    resendAlreadyVerified: "هذا البريد مُفعّل مسبقاً. يمكنك تسجيل الدخول.",
    resendSendFailed:
      "تعذّر إرسال البريد. تحقق من الإعدادات أو راجع سجل الخادم (في التطوير يُطبع الرابط في الطرفية).",
  },
  verifyEmail: {
    invalidTitle: "رابط غير صالح",
    invalidBody: "لم نجد رمز التحقق. اطلب إعادة التسجيل أو راجع الرابط في البريد.",
    goLogin: "الذهاب لتسجيل الدخول",
    linkExpired: "انتهت صلاحية رابط التحقق أو غير صالح",
  },
  verifyPhone: {
    title: "تحقق من الجوال",
    subtitle:
      "أدخل رقم جوالك المسجّل، ثم الرمز المكوّن من 6 أرقام المرسل برسالة SMS نصية.",
    identifierLabel: "الجوال أو البريد",
    codeLabel: "رمز التحقق",
    submit: "تأكيد",
    submitPending: "جاري التحقق…",
    invalid: "بيانات غير صالحة",
    badCode: "رمز غير صحيح أو منتهٍ",
  },
  dashboard: {
    title: "ابدأ مع عَمارتي",
    subtitle: "انضم إلى مبنى قائم برمز المبنى ورقم شقتك.",
    titleMy: "مبانيك",
    subtitleMy: "اختر المبنى لفتح لوحته (الصيانة، التصويت، الإعلانات).",
    createBuildingDisabled: "إنشاء مبنى جديد غير متاح من التطبيق. استخدم رمز المبنى للانضمام.",
    createBuilding: "إنشاء مبنى جديد",
    addressHelp:
      "اكتب وصفًا نصّيًا لموقع المبنى (الشارع أو الحي) مع المدينة — كما تناسبك.",
    nationalAddressTitle: "العنوان الوطني",
    nationalAddressHelp:
      "أدخل بيانات العنوان الوطني وفق معايير البريد السعودي (العنوان الوطني).",
    nationalAddressInvalid:
      "تحقق من حقول العنوان الوطني: المنطقة، المدينة، الحي، الشارع، رقم المبنى، والرمز البريدي (5 أرقام).",
    addressLine: "العنوان",
    addressLinePh: "مثال: حي النخيل، شارع الملك فهد",
    name: "اسم العمارة",
    namePh: "مثال: عمارة النور",
    region: "المنطقة",
    regionPh: "مثال: منطقة الرياض",
    city: "المدينة",
    cityPh: "مثال: الرياض",
    district: "الحي",
    streetName: "اسم الشارع",
    buildingNumber: "رقم المبنى",
    additionalNumber: "الرقم الإضافي (اختياري)",
    postalCode: "الرمز البريدي (5 أرقام)",
    shortAddressCode: "الرمز المختصر (8 خانات، اختياري)",
    unitLabel: "رقم شقتك",
    unitPh: "مثال: 303",
    createSubmit: "إنشاء المبنى وربط شقتك",
    joinCard: "الانضمام برمز المبنى",
    joinHint: "أدخل رمز المبنى ورقم شقتك.",
    inviteCode: "رمز المبنى",
    unitNumber: "رقم الشقة",
    joinSubmit: "انضمام",
    buildingsCard: "مبانيك",
    noBuildings: "لا توجد مبانٍ بعد. أنشئ مبنى أو انضم برمز.",
    unit: "شقة",
    owner: "مالك",
    tenant: "مستأجر",
    supervisor: "مشرف",
    open: "فتح",
    openBuilding: "فتح لوحة المبنى",
    openBuildingAria: "فتح لوحة المبنى",
    createAnotherBuilding: "إنشاء مبنى آخر",
    backToDashboard: "العودة للوحة الرئيسية",
  },
  buildingLayout: {
    building: "المبنى",
    inviteCode: "رمز الدعوة",
    mapLink: "فتح الموقع على الخريطة",
    allBuildings: "كل المبانى",
  },
  buildingNav: {
    overview: "نظرة عامة",
    maintenance: "صيانة",
    votes: "تصويت",
    announcements: "إعلانات",
    chat: "محادثة جماعية",
    passport: "جواز الشقة",
    invite: "دعوات",
    supervisor: "لوحة المشرف",
  },
  buildingHome: {
    membershipInBuilding: "عضويتك في المبنى",
    youSupervisor: "أنت المشرف",
    currentSupervisor: "المشرف الحالي",
    noSupervisor:
      "لا يوجد مشرف محدد. يمكن لمنشئ المبنى بدء تصويت اختيار المشرف من قسم التصويت.",
    unitPrefix: "شقة",
    assignHint: "تعيين مشرف (صلاحية منشئ المبنى)",
    chooseMember: "اختر عضواً",
    assignSubmit: "تعيين كن مشرف",
    startVote: "بدء تصويت لاختيار مشرف",
    ownersRequired: "يتطلب مالكين فأكثر",
    shortcuts: "اختصارات سريعة",
    linkMaintenance: "تقديم طلب صيانة",
    linkVotes: "التصويتات",
    linkInvite: "رمز المبنى",
    linkPassport: "جواز الشقة",
    linkPublicCode: "مشاركة رمز المبنى",
    overviewSection: "نظرة عامة",
    aiAssistantSection: "المساعد الذكي",
    socialSection: "محادثة السكان والإعلانات",
    chatTitle: "محادثة السكان",
    announcementsTitle: "آخر الإعلانات",
    openChat: "محادثة جماعية",
    openAnnouncements: "فتح الإعلانات",
    openAssistant: "مساعد ذكي",
    openInvite: "مشاركة رمز المبنى",
    noChatYet: "لا رسائل بعد — ابدأ المحادثة من قسم المحادثة.",
    noAnnouncementsYet: "لا إعلانات بعد.",
    moreCount: "المزيد",
    supervisorOverviewTitle: "صحة المبنى — لوحة المشرف",
    supervisorOverviewHint:
      "ملخّص للمشرف: السكور الشهري من سجل الصيانة (بدون شاشة تنبيهات منفصلة).",
  },
  maintenance: {
    newRequest: "طلب صيانة جديد",
    aiHint:
      "يحلّل وصف المشكلة (شخصية أو مجتمعية)، يقدّر نافذة زمنية للصيانة والحد الأقصى للانتظار، ثم يقترح شركات صيانة. للصيانة المجتمعية يُفتح تصويت تلقائياً على الشركات المقترحة.",
    mlConnected: "خادم تحليل ذكي متصل — يُكمّل المنطق المحلي في التطبيق.",
    mlLocalOnly:
      "التحليل يعمل محلياً. لتفعيل نموذج Colab: شغّل npm run ml:serve واضبط MAINTENANCE_ML_API_URL في .env.local ثم أعد تشغيل Next.",
    type: "النوع",
    scopePersonal: "صيانة شخصية (شقتك)",
    scopeCommunity: "صيانة مجتمعية (مشتركة)",
    title: "عنوان مختصر",
    problem: "وصف المشكلة",
    submitAi: "إرسال مع تحليل وتوصيات الذكاء الاصطناعي",
    requests: "الطلبات",
    noneRequests: "لا طلبات صيانة بعد.",
    personalUnit: "شخصي — شقة",
    community: "مجتمعي",
    status: "المرحلة",
    statusInProgress: "قيد المعالجة",
    statusDone: "مكتمل",
    statusCancelled: "ملغى",
    analysis: "تحليل",
    suggestions: "توصيات",
    aiTag: "تحليل ذكاء اصطناعي",
    aiCompanies: "شركات صيانة مقترحة:",
    companySuggestion: "اقتراح",
    startCompanyVote: "بدء تصويت لاختيار شركة صيانة",
    companyVoteOpen: "يوجد تصويت جاري لشركة الصيانة — تابع من قسم «تصويت».",
    communityVotePending: "يُنشأ تصويت الشركات تلقائياً عند توفر ترشيحات مقترحة.",
    pickVendor: "اختر شركة صيانة من القائمة:",
    confirmVendor: "تأكيد الاختيار",
    selectedVendorLabel: "الشركة المختارة",
    scopeLabelPersonal: "شخصي",
    scopeLabelCommunity: "مجتمعي",
  },
  assistant: {
    title: "المساعد الذكي",
    welcomeUser: "مرحبًا {name}",
    roleOwner: "مالك شقة",
    roleTenant: "مستأجر",
    welcomeMessage:
      "👋 أهلًا بك في عمارتي!\n\nأنا مساعدك الذكي، جاهز أسهّل عليك إدارة شقتك وعمارتك بخطوات بسيطة وواضحة.\n\nمن متابعة الصيانة، واستقبال البلاغات، وتنظيم السكن... إلى متابعة المدفوعات والتنبيهات — كل شيء عندك في مكان واحد 👇\n\nإذا احتجت أي مساعدة، اسألني مباشرة... وأنا هنا دائماً لخدمتك ✨\n\nخلينا نبدأ معاً بتجربة إدارة أسهل، أسرع، وأذكى مع عمارتي 🏢💙",
    quickStatus: "معلومات شقتي",
    quickMaintenance: "عرض طلبات الصيانة",
    placeholder: "اكتب رسالتك...",
    demoReply:
      "سأساعدك في استخدام التطبيق خطوة بخطوة. جرّب من الشريط السفلي: الرئيسية، الصيانة، التصويت، والحساب. اسألني عن الانضمام برمز المبنى أو تقديم طلب صيانة.",
  },
  chat: {
    title: "محادثة السكان",
    conversationsTitle: "المحادثات",
    welcomeUser: "مرحبًا {name}",
    roleOwner: "مالك شقة",
    roleTenant: "مستأجر",
    tabResidents: "السكان",
    tabGroup: "محادثة جماعية",
    emptyGroup: "لا رسائل بعد — اكتب أول رسالة للسكان أدناه.",
    emptyResidents: "لا يوجد سكان مسجّلون في المبنى بعد.",
    placeholder: "اكتب رسالتك...",
    send: "إرسال",
    hint: "",
    buildingAdmin: "إدارة المبنى",
  },
  votes: {
    title: "التصويتات",
    titleSupervisor: "تصويت اختيار المشرف",
    titleCompany: "تصويت شركات الصيانة (الأعطال المجتمعية)",
    titleOther: "تصويتات أخرى",
    kindsTitle: "خيارات التصويت",
    kindsHint: "",
    kindSupervisorTitle: "تصويت لاختيار مشرف",
    kindSupervisorDesc: "يحق لمنشئ المبنى فقط بدء تصويت اختيار المشرف.",
    kindCompanyTitle: "تصويت شركة صيانة (مجتمعي)",
    kindCompanyDesc:
      "عند تقديم طلب صيانة مجتمعي يُنشأ تصويت تلقائياً على الشركات المقترحة.",
    creatorOnlyHint: "يحق لمنشئ المبنى فقط بدء تصويت المشرف.",
    openMaintenance: "فتح قسم الصيانة لاختيار طلب",
    typeSupervisor: "مشرف",
    typeCompany: "شركة صيانة",
    typeLegacyPoll: "تصويت (أرشيف)",
    open: "مفتوح",
    closed: "مغلق",
    statusActive: "جاري",
    statusEnded: "منتهٍ",
    ends: "ينتهي",
    votes: "صوت",
    vote: "صوّت",
    yourVote: "صوتك هنا",
    startSupervisor: "بدء تصويت المشرف",
    closeSupervisor: "إغلاق وتعيين المشرف الفائز",
    closeCompany: "إغلاق التصويت وتسجيل الشركة الفائزة",
    none: "لا تصويتات بعد.",
  },
  supervisor: {
    only: "هذه الصفحة للمشرف فقط.",
    panelTitle: "لوحة المشرف",
    refreshTitle: "تحديث السكور والتنبؤات",
    refreshP1:
      "زر «تحديث الآن» يُحدّث سكور صحة المبنى الشهري من سجل طلبات الصيانة.",
    refreshBtn: "تحديث الآن",
    scoreTitle: "سجل السكور الشهري",
    scoreEmpty: "اضغط «تحديث الآن» لإنشاء أول سجل.",
    scoreScaleRange: "النطاق",
    scoreScaleLabel: "التصنيف",
    scoreScaleDesc: "الوصف",
  },
  announcements: {
    new: "إعلان جديد",
    titlePh: "عنوان الإعلان",
    bodyPh: "تفاصيل...",
    publish: "نشر",
    recent: "آخر الإعلانات",
    delete: "حذف",
  },
  passport: {
    title: "جواز الشقة",
    subtitle: "",
    none: "لا سجلات بعد.",
  },
  invitePage: {
    publicCode: "رمز المبنى العام",
    shareHintBefore: "شارك الرمز مع الجيران لينضموا برقم شقتهم:",
    publicOnlyHint:
      "شارك رمز المبنى أعلاه — ينضم الجيران من شاشة الانضمام برقم شقتهم.",
    tenantCard: "دعوات المستأجرين",
    tenantOnly:
      "حسابك مستأجر — يمكنك مشاركة رمز المبنى العام مع باقي السكان.",
  },
  join: {
    invalidTitle: "رابط غير صالح",
    expired: "قد يكون منتهي الصلاحية.",
    backDashboard: "العودة للوحة التحكم",
    inviteTitle: "دعوة للانضمام",
    building: "المبنى",
    unit: "الشقة",
    kind: "النوع",
    accept: "قبول والانضمام",
  },
  profile: {
    title: "الحساب",
    subtitle: "",
    accountTitle: "بيانات الحساب",
    name: "الاسم",
    email: "البريد",
    phone: "الجوال",
    save: "حفظ التغييرات",
    saving: "جاري الحفظ…",
    saved: "تم حفظ بياناتك.",
    invalidForm: "بيانات غير صالحة. يجب أن يكون الاسم حرفين فأكثر.",
    emailVerifiedYes: "بريدك مؤكَّد.",
    emailVerifiedNo: "البريد غير مؤكَّد بعد.",
    emailOptionalPlaceholder: "يمكن إضافة بريد لاحقًا",
    resendVerification: "إعادة إرسال رابط التأكيد",
    settingsTitle: "الإعدادات",
    settingsHint: "المظهر والإشعارات تُحفظ على هذا الجهاز.",
    themeLabel: "المظهر",
    themeToggle: "تبديل المظهر (فاتح / داكن)",
    themeLight: "فاتح",
    themeDark: "داكن",
    residentsVisibilityLabel: "الظهور في قائمة السكان",
    residentsVisibleOn: "يظهر اسمك في قائمة سكان المبنى",
    residentsVisibleOff: "اسمك مخفي عن قائمة السكان",
    notificationsLabel: "إشعارات المتصفح",
    notificationsOn: "مفعّلة",
    notificationsOff: "متوقفة",
    notificationsHint: "",
    smsSendFailed: "تعذّر إرسال رسالة التحقق. جرّب لاحقاً أو راجع إعداد Twilio.",
    smsNotConfigured:
      "إرسال SMS غير مهيأ على الخادم — الرمز يظهر في سجل التشغيل للتطوير فقط.",
    logout: "تسجيل الخروج",
    memberSince: "عضو منذ",
    passportTitle: "جواز الشقة",
    passportHint: "",
    passportNoUnits: "لم تنضم إلى أي مبنى بعد.",
    passportNoEvents: "لا سجلات لهذه الوحدة بعد.",
    passportOpen: "فتح جواز الوحدة",
    phoneVerifiedYes: "الجوال مؤكَّد.",
    phoneVerifiedNo: "الجوال غير مؤكَّد.",
    sendPhoneOtp: "إرسال رمز تحقق للجوال",
    needPhoneForOtp: "أدخل رقم الجوال واحفظ التغييرات قبل طلب رمز التحقق.",
    notificationsCardTitle: "الإعدادات",
  },
} as const;

type Messages = typeof AR;

const EN = {
  landing: {
    nameAr: "عماراتي",
    tagline: "Smart building management",
    desc: "Smart building management",
    login: "Log in",
    register: "Sign up",
    create: "Create building",
    langLabel: "عربي",
    logoAlt: "Amarati",
  },
  login: {
    title: "Log in",
    subtitle: "",
    emailVerified: "Your email is verified. You can sign in now.",
    identifier: "Phone or email",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    submit: "Sign in",
    submitPending: "Signing in…",
    noAccount: "Don’t have an account?",
    signUp: "Create a new account",
    noAccountFull: "No account with this phone number or email.",
    verifyEmailFirst:
      "Please confirm your email using the link we sent, or confirm your phone with the OTP on the “Verify phone” page, before signing in.",
    invalidForm: "Invalid data",
    invalidCredentials: "Incorrect phone/email or password.",
    passwordMinForNew: "New accounts need a password of at least 6 characters.",
    resendVerifyHint: "Didn’t get the email? Resend the link from the verification page.",
    resendVerifyLink: "Resend confirmation link",
  },
  signup: {
    chooseTitle: "Create your account",
    chooseSubtitle: "Join your building with the building code and unit number.",
    choiceCreateTitle: "Register a new building",
    choiceCreateDesc: "Register a new building and share the invite code with residents.",
    choiceJoinTitle: "Join a building",
    choiceJoinDesc: "Join your building with the building code and unit number.",
    haveAccount: "Already have an account?",
    backLogin: "Log in",
    yourInfoTitle: "Your details",
    buildingInfoTitle: "Building details",
    joinInfoTitle: "Join details",
    submitCreate: "Create account & register building",
    submitJoin: "Create account & join",
    submitPending: "Working…",
    headerCreate: "Create account — new building",
    headerJoin: "Create account — join building",
    inviteCodeNotFound: "Building code is invalid or not found.",
    addressInvalid:
      "Check the building name, unit number, and national address fields (region, city, district, street, building number, postal code).",
  },
  register: {
    title: "Join Amarati — resident account",
    name: "Name",
    email: "Email (optional)",
    phone: "Phone (required)",
    password: "Password",
    submit: "Create account",
    submitPending: "Creating account…",
    hasAccount: "Already have an account?",
    login: "Log in",
    invalidForm: "Invalid data",
    emailTaken: "This email is already registered",
    phoneTaken: "This phone number is already registered",
    verifyAfterRegister:
      "After you sign up we send a confirmation link to your email. Open it, then sign in.",
    verifySendFailed:
      "Could not send the verification email. See the message below or the server log.",
    verifySendFailedNoUrl:
      "Could not build the verification link. Set NEXT_PUBLIC_APP_URL in .env (e.g. http://localhost:3000).",
    verifySendFailedNoSender:
      "Production requires a real RESEND_API_KEY from resend.com/api-keys. Or use npm run dev to print the link in the terminal.",
    verifySendFailedResend:
      "Resend rejected the send. Check Logs at resend.com/emails — often an invalid key, a disposable test address (e.g. @example.com), or an invalid from address.",
    verifySendFailedResendTestingRecipient:
      "Resend test mode: with onboarding@resend.dev you may only send to the same email as your Resend account. Register using that address, or verify a domain in Resend → Domains and set RESEND_FROM_EMAIL on that domain.",
    verifySendFailedResendFromDomain:
      "RESEND_FROM_EMAIL must use a domain you verified in Resend → Domains (SPF/DKIM). Or use onboarding@resend.dev for initial testing.",
    verifySendFailedResendInvalidKey:
      "Resend rejected the API key (revoked, wrong, or missing). Create a new key with Full access at resend.com/api-keys, update RESEND_API_KEY, and restart the server.",
    verifySendFailedResendBlockedEmail:
      "That recipient domain is blocked for testing (e.g. @example.com). Use a real inbox or a Resend test address like delivered@resend.dev.",
  },
  registerCheckEmail: {
    title: "Check your email",
    bodyBefore: "We sent a confirmation link. Open it, then return to",
    loginLink: "log in",
    bodyAfter: ".",
    resendTitle: "Resend link",
    resendHint: "Enter the email you registered with to receive a new link (valid 24 hours).",
    resendEmailLabel: "Email",
    resendSubmit: "Send link",
    resentOk: "If there is an unverified account for that address, we sent a new link.",
    resendInvalidEmail: "Enter a valid email address",
    resendAlreadyVerified: "This email is already verified. You can sign in.",
    resendSendFailed:
      "Could not send the email. Check your settings or the server log (in development the link is printed in the terminal).",
  },
  verifyEmail: {
    invalidTitle: "Invalid link",
    invalidBody: "No verification token found. Register again or use the link from your email.",
    goLogin: "Go to log in",
    linkExpired: "This verification link has expired or is invalid.",
  },
  verifyPhone: {
    title: "Verify phone",
    subtitle:
      "Enter your registered phone number, then the 6‑digit code sent by SMS text message.",
    identifierLabel: "Phone or email",
    codeLabel: "Verification code",
    submit: "Confirm",
    submitPending: "Verifying…",
    invalid: "Invalid data",
    badCode: "Wrong or expired code",
  },
  dashboard: {
    title: "Get started with Amarati",
    subtitle: "Join an existing building with a code and your unit number.",
    titleMy: "Your buildings",
    subtitleMy: "Pick a building to open its dashboard (maintenance, voting, announcements).",
    createBuildingDisabled:
      "Creating a new building is not available in the app. Use a building code to join.",
    createBuilding: "Create a new building",
    addressHelp: "Describe the street or neighbourhood plus city — plain text.",
    nationalAddressTitle: "National address",
    nationalAddressHelp:
      "Enter your national address per Saudi Post standards (National Address).",
    nationalAddressInvalid:
      "Check national address fields: region, city, district, street, building number, and 5-digit postal code.",
    addressLine: "Street / area",
    addressLinePh: "e.g. Al-Nakheel district, King Fahd Road",
    name: "Building name",
    namePh: "e.g. Al-Noor Tower",
    region: "Region",
    regionPh: "e.g. Riyadh Region",
    city: "City",
    cityPh: "e.g. Riyadh",
    district: "District",
    streetName: "Street name",
    buildingNumber: "Building number",
    additionalNumber: "Additional number (optional)",
    postalCode: "Postal code (5 digits)",
    shortAddressCode: "Short address code (8 chars, optional)",
    unitLabel: "Your unit number",
    unitPh: "e.g. 303",
    createSubmit: "Create building and link my unit",
    joinCard: "Join with building code",
    joinHint: "Enter the building code and your unit number.",
    inviteCode: "Building code",
    unitNumber: "Unit number",
    joinSubmit: "Join",
    buildingsCard: "Your buildings",
    noBuildings: "No buildings yet. Create one or join with a code.",
    unit: "Unit",
    owner: "Owner",
    tenant: "Tenant",
    supervisor: "Supervisor",
    open: "Open",
    openBuilding: "Open building dashboard",
    openBuildingAria: "Open building dashboard",
    createAnotherBuilding: "Register another building",
    backToDashboard: "Back to dashboard",
  },
  buildingLayout: {
    building: "Building",
    inviteCode: "Invite code",
    mapLink: "Open on map",
    allBuildings: "All buildings",
  },
  buildingNav: {
    overview: "Overview",
    maintenance: "Maintenance",
    votes: "Votes",
    announcements: "Announcements",
    chat: "Group chat",
    passport: "Unit passport",
    invite: "Invites",
    supervisor: "Supervisor",
  },
  buildingHome: {
    membershipInBuilding: "Your membership",
    youSupervisor: "You are the supervisor",
    currentSupervisor: "Current supervisor",
    noSupervisor:
      "No supervisor assigned yet. The building creator can start a supervisor vote under Votes.",
    unitPrefix: "Unit",
    assignHint: "Assign supervisor (building creator only)",
    chooseMember: "Choose a member",
    assignSubmit: "Set as supervisor",
    startVote: "Start vote to elect supervisor",
    ownersRequired: "Requires two or more owners",
    shortcuts: "Quick shortcuts",
    linkMaintenance: "Submit maintenance request",
    linkVotes: "Votes",
    linkInvite: "Building code",
    linkPassport: "Unit passport",
    linkPublicCode: "Share building code",
    overviewSection: "Overview",
    aiAssistantSection: "AI Assistant",
    socialSection: "Chat & announcements",
    chatTitle: "Resident chat",
    announcementsTitle: "Latest announcements",
    openChat: "Group chat",
    openAnnouncements: "Open announcements",
    openAssistant: "Smart assistant",
    openInvite: "Share building code",
    noChatYet: "No messages yet — open the chat to start a conversation.",
    noAnnouncementsYet: "No announcements yet.",
    moreCount: "more",
    supervisorOverviewTitle: "Building health — supervisor panel",
    supervisorOverviewHint:
      "Quick supervisor summary: monthly health score from maintenance history (no separate “alert” feed).",
  },
  maintenance: {
    newRequest: "New maintenance request",
    aiHint:
      "The model reads your description (personal or community), estimates a maintenance window and a maximum wait, then suggests companies. Community requests automatically open a vote on those companies.",
    mlConnected:
      "An external prediction service is configured — combined with Amarati analysis on-device.",
    mlLocalOnly:
      "Analysis runs locally only. For Colab: run npm run ml:serve, set MAINTENANCE_ML_API_URL in .env.local, restart Next.",
    type: "Type",
    scopePersonal: "Personal (your unit)",
    scopeCommunity: "Community (shared)",
    title: "Short title",
    problem: "Problem description",
    submitAi: "Submit with AI analysis & recommendations",
    requests: "Requests",
    noneRequests: "No maintenance requests yet.",
    personalUnit: "Personal — unit",
    community: "Community",
    status: "Status",
    statusInProgress: "In progress",
    statusDone: "Done",
    statusCancelled: "Cancelled",
    analysis: "Analysis",
    suggestions: "Suggestions",
    aiTag: "AI analysis",
    aiCompanies: "Suggested maintenance companies:",
    companySuggestion: "Suggestion",
    startCompanyVote: "Start vote to pick a maintenance company",
    companyVoteOpen: "A maintenance company vote is in progress — see the Voting tab.",
    communityVotePending: "A company vote is created automatically when suggestions are available.",
    pickVendor: "Pick a maintenance company:",
    confirmVendor: "Confirm choice",
    selectedVendorLabel: "Selected company",
    scopeLabelPersonal: "Personal",
    scopeLabelCommunity: "Community",
  },
  assistant: {
    title: "Smart assistant",
    welcomeUser: "Welcome, {name}",
    roleOwner: "Unit owner",
    roleTenant: "Tenant",
    welcomeMessage:
      "👋 Welcome to Amarati!\n\nI'm your smart assistant, here to make managing your unit and building simple and clear.\n\nFrom maintenance and reports to housing organization, payments, and alerts — everything in one place 👇\n\nAsk me anytime — I'm always here to help ✨\n\nLet's start an easier, faster, smarter building experience with Amarati 🏢💙",
    quickStatus: "My unit overview",
    quickMaintenance: "View maintenance requests",
    placeholder: "Write your message…",
    demoReply:
      "I'll guide you through the app step by step. Use the bottom bar: Home, Maintenance, Votes, and Account. Ask about joining with a building code or filing maintenance.",
  },
  chat: {
    title: "Resident chat",
    conversationsTitle: "Conversations",
    welcomeUser: "Welcome, {name}",
    roleOwner: "Unit owner",
    roleTenant: "Tenant",
    tabResidents: "Residents",
    tabGroup: "Group chat",
    emptyGroup: "No messages yet — send the first one below.",
    emptyResidents: "No residents registered in this building yet.",
    placeholder: "Write your message…",
    send: "Send",
    hint: "",
    buildingAdmin: "Building admin",
  },
  votes: {
    title: "Votes",
    titleSupervisor: "Supervisor election votes",
    titleCompany: "Maintenance-company votes (community issues)",
    titleOther: "Other votes",
    kindsTitle: "Vote types",
    kindsHint: "",
    kindSupervisorTitle: "Supervisor election",
    kindSupervisorDesc: "Only the building creator can start supervisor voting.",
    kindCompanyTitle: "Maintenance-company vote (community)",
    kindCompanyDesc:
      "When someone files a community maintenance request, a vote is created automatically on suggested companies.",
    creatorOnlyHint: "Only the building creator can start a supervisor vote.",
    openMaintenance: "Open maintenance to pick a request",
    typeSupervisor: "Supervisor",
    typeCompany: "Maintenance company",
    typeLegacyPoll: "Poll (archive)",
    open: "Open",
    closed: "Closed",
    statusActive: "Active",
    statusEnded: "Ended",
    ends: "Ends",
    votes: "votes",
    vote: "Vote",
    yourVote: "Your vote",
    startSupervisor: "Start supervisor vote",
    closeSupervisor: "Close and assign winning supervisor",
    closeCompany: "Close vote and record the winning company",
    none: "No votes yet.",
  },
  supervisor: {
    only: "Supervisors only.",
    panelTitle: "Supervisor panel",
    refreshTitle: "Refresh score & predictions",
    refreshP1:
      "“Update now” refreshes the monthly building health score from the maintenance request log.",
    refreshBtn: "Update now",
    scoreTitle: "Monthly score log",
    scoreEmpty: "Click “Update now” to create the first record.",
    scoreScaleRange: "Range",
    scoreScaleLabel: "Rating",
    scoreScaleDesc: "Description",
  },
  announcements: {
    new: "New announcement",
    titlePh: "Title",
    bodyPh: "Details…",
    publish: "Publish",
    recent: "Recent announcements",
    delete: "Delete",
  },
  passport: {
    title: "Digital passport — unit",
    subtitle: "",
    none: "No records yet.",
  },
  invitePage: {
    publicCode: "Public building code",
    shareHintBefore: "Share this code so neighbours can join with their unit number:",
    publicOnlyHint:
      "Share the building code above — neighbours join from the Join screen with their unit number.",
    tenantCard: "Tenant invites",
    tenantOnly:
      "You are a tenant — you can share the public building code with other residents.",
  },
  join: {
    invalidTitle: "Invalid link",
    expired: "It may have expired.",
    backDashboard: "Back to dashboard",
    inviteTitle: "Invitation to join",
    building: "Building",
    unit: "Unit",
    kind: "Role",
    accept: "Accept and join",
  },
  profile: {
    title: "Account",
    subtitle: "",
    accountTitle: "Account details",
    name: "Name",
    email: "Email",
    phone: "Phone",
    save: "Save changes",
    saving: "Saving…",
    saved: "Your profile has been updated.",
    invalidForm: "Invalid data. Name must be at least 2 characters.",
    emailVerifiedYes: "Email verified.",
    emailVerifiedNo: "Email not verified yet.",
    emailOptionalPlaceholder: "You can add an email anytime",
    resendVerification: "Resend confirmation link",
    settingsTitle: "Settings",
    settingsHint: "Theme and notifications stay on this device.",
    themeLabel: "Theme",
    themeToggle: "Toggle theme (light / dark)",
    themeLight: "Light",
    themeDark: "Dark",
    residentsVisibilityLabel: "Show in residents list",
    residentsVisibleOn: "Your name is visible in the building residents list",
    residentsVisibleOff: "Your name is hidden from the residents list",
    notificationsLabel: "Browser notifications",
    notificationsOn: "On",
    notificationsOff: "Off",
    notificationsHint: "",
    smsSendFailed: "Could not send the SMS verification code. Try again later or check Twilio settings.",
    smsNotConfigured:
      "SMS is not configured on the server — the code is printed in server logs for development only.",
    logout: "Log out",
    memberSince: "Member since",
    passportTitle: "Unit passport",
    passportHint: "",
    passportNoUnits: "You have not joined any building yet.",
    passportNoEvents: "No records for this unit yet.",
    passportOpen: "Open unit passport",
    phoneVerifiedYes: "Phone verified.",
    phoneVerifiedNo: "Phone not verified yet.",
    sendPhoneOtp: "Send verification code to phone",
    needPhoneForOtp: "Enter your phone number and save before requesting a code.",
    notificationsCardTitle: "Settings",
  },
} as unknown as Messages;

export function ui(locale: AppLocale): Messages {
  return locale === "en" ? EN : AR;
}

export function pickDateLocale(locale: AppLocale): string {
  return locale === "en" ? "en-US" : "ar-SA";
}
