# -*- coding: utf-8 -*-
"""Maintenance_Predictive_&_Recommendation_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFWwkmam1MXkW5FBLrQR77OiDleyKLMy
"""

import pandas as pd
import numpy as np
n = 8000

data = pd.DataFrame({

    "house_age": np.random.randint(1, 40, n),

    "humidity": np.random.randint(30, 90, n),

    "rainfall_level": np.random.randint(0, 50, n),

    "water_pressure": np.random.randint(30, 80, n),

    "electric_load": np.random.randint(1000, 5000, n),

    "soil_movement": np.random.randint(0, 5, n),

    "maintenance_count": np.random.randint(0, 10, n),

    "last_maintenance_days": np.random.randint(10, 500, n)

})

conditions = [

    (data["water_pressure"] > 70),

    (data["humidity"] > 80),

    (data["electric_load"] > 4200),

    (data["maintenance_count"] < 2),

    (data["rainfall_level"] > 35)

]

choices = [

    "Water_Leakage",

    "Wall_Crack",

    "Electrical_Issue",

    "Drainage_Blockage",

    "Roof_Leakage"

]

data["failure_type"] = np.select(conditions, choices, default="No_Issue")

data.head()

data.to_csv("home_maintenance_dataset.csv", index=False)

data["failure_type"].value_counts()

data = pd.read_csv("home_maintenance_dataset.csv")
data.head()

data.describe()

data.info()

data.isnull().sum()

data.duplicated().sum()

X = data.drop("failure_type", axis=1)

y = data["failure_type"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

sample = [[
25,  # house_age
70,  # humidity
15,  # rainfall_level
60,  # water_pressure
4500, # electric_load
1,   # soil_movement
1,   # maintenance_count
300  # last_maintenance_days
]]

prediction = model.predict(sample)

print("Predicted Issue:", prediction[0])

import joblib

joblib.dump(model, "home_failure_model.pkl")

import pandas as pd

services = pd.DataFrame({

"service_type":[
"Electrical_Issue",
"Electrical_Issue",
"Water_Leakage",
"Water_Leakage",
"Roof_Leakage",
"Wall_Crack",
"Drainage_Blockage",
"Drainage_Blockage"
],

"company":[
"Makkah Electric Services",
"Al Haram Electric",
"Zamzam Plumbing",
"Al Noor Plumbing",
"Haram Roof Repair",
"Makkah Wall Repair",
"Zamzam Drain Service",
"Al Makkah Drain Fix"
],

"rating":[
4.7,
4.6,
4.8,
4.5,
4.6,
4.3,
4.4,
4.2
],

"latitude":[
21.3891,
21.4000,
21.4225,
21.4180,
21.4300,
21.4100,
21.4230,
21.4150
],

"longitude":[
39.8579,
39.8600,
39.8262,
39.8300,
39.8350,
39.8200,
39.8250,
39.8220
]

})

services.to_csv("makkah_services.csv", index=False)

services = pd.read_csv("makkah_services.csv")

services.head()

def recommend_services(issue):

    services = pd.read_csv("makkah_services.csv")

    filtered = services[
        services["service_type"] == issue
    ]

    filtered = filtered.sort_values(
        by="rating",
        ascending=False
    )

    return filtered.head(3)

recommend_services("Water_Leakage")

prediction = model.predict(sample)[0]

recommendations = recommend_services(prediction)

print(recommendations)

"""**Example for project without simulation**"""

# user input
user_input = {
    "house_age": 25,
    "humidity": 75,
    "water_pressure": 65,
    "electric_load": 4500,
    "soil_movement": 3,
    "maintenance_count": 2,
    "last_maintenance_days": 180
}

# نحدد العطل مباشرة (simulate prediction)
predicted_issue = "Electrical_Issue"

# Dataset الفنيين في مكة
services = pd.DataFrame({
    "service_type":[
        "Electrical_Issue","Electrical_Issue",
        "Water_Leakage","Water_Leakage",
        "Roof_Leakage","Wall_Crack",
        "Drainage_Blockage"
    ],
    "company":[
        "Makkah Electric Services","Al Haram Electric",
        "Zamzam Plumbing","Al Noor Plumbing",
        "Haram Roof Repair","Makkah Wall Repair",
        "Zamzam Drain Service"
    ],
    "rating":[4.7,4.6,4.8,4.5,4.6,4.3,4.4],
    "latitude":[21.3891,21.4000,21.4225,21.4180,21.4300,21.4100,21.4230],
    "longitude":[39.8579,39.8600,39.8262,39.8300,39.8350,39.8200,39.8250]
})

# Recommendation Function
def recommend_services(issue):
    filtered = services[services["service_type"] == issue]
    filtered = filtered.sort_values(by="rating", ascending=False)
    return filtered.head(3)

recommendations = recommend_services(predicted_issue)

print("Predicted Issue:", predicted_issue)
print("\nRecommended Technicians in Makkah:")
print(recommendations[["company","rating","latitude","longitude"]])

import joblib
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Ensure the directory exists before saving
os.makedirs('/content/drive/MyDrive/Dataset Course', exist_ok=True)

joblib.dump(model, "/content/drive/MyDrive/Dataset Course/modelMaintenance.joblib")